const path = require("path");
const swaggerAutogen = require('swagger-autogen')()
const currentPath = path.join(__dirname, './.env')
require("dotenv").config({path: currentPath});

const PORT = process.env.PORT || 2327;
const HOST = process.env.HOST || 'localhost';
const doc = {
  info: {
    version: "1.0.0",
    title: "Mockup server API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: `${HOST}:${PORT}`,
  basePath: "/",
  schemes: ['http', 'https'],
}

const outputFile = path.join(__dirname, './swagger_output.json');
const endpointsFiles = [path.join(__dirname, './server_detector.js')]

swaggerAutogen(outputFile, endpointsFiles, doc)
